version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - mv install.bat install.sh
      - chmod +x install.sh
      - bash ./install.sh

mkdocs:
  configuration: mkdocs.yml

python:
  install:
  - requirements: docs/requirements.txt